import { Slider, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <image> texture <=> image.source;
    callback request-change-angle(int);

    title: "Slint/KDGpu Example";

    VerticalBox {
        Text {
            text: "Hello from Slint! The scene below is rendered with KDGpu.";
        }

        HorizontalBox {
            Text {
                text: "Angle";
            }

            slider := Slider {
                value: 0;
                minimum: 0;
                maximum: 360;
                changed(value) => {
                    root.request-change-angle(value);
                }
            }
        }

        image := Image {
            preferred-width: 600px;
            preferred-height: 600px;
            width: 100%;
            height: 100%;
        }
     }
}
